//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIEWpf.FileService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EStatusOfOperation", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum EStatusOfOperation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESSFULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FILEDOESNOTEXISTS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILWHILEBACKUP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILWILESTOPSERV = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IFileTransfer")]
    public interface IFileTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/FileInstall", ReplyAction="http://tempuri.org/IFileTransfer/FileInstallResponse")]
        MIEWpf.FileService.EStatusOfOperation FileInstall(string filePath, string[] pathOfExistsFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/FileInstall", ReplyAction="http://tempuri.org/IFileTransfer/FileInstallResponse")]
        System.Threading.Tasks.Task<MIEWpf.FileService.EStatusOfOperation> FileInstallAsync(string filePath, string[] pathOfExistsFiles);
        
        // CODEGEN: Generating message contract since the operation UploadFileToServer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/UploadFileToServer", ReplyAction="http://tempuri.org/IFileTransfer/UploadFileToServerResponse")]
        MIEWpf.FileService.UploadFileToServerResponse UploadFileToServer(MIEWpf.FileService.FileData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/UploadFileToServer", ReplyAction="http://tempuri.org/IFileTransfer/UploadFileToServerResponse")]
        System.Threading.Tasks.Task<MIEWpf.FileService.UploadFileToServerResponse> UploadFileToServerAsync(MIEWpf.FileService.FileData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/GetDirectoriesWithFile", ReplyAction="http://tempuri.org/IFileTransfer/GetDirectoriesWithFileResponse")]
        string[] GetDirectoriesWithFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/GetDirectoriesWithFile", ReplyAction="http://tempuri.org/IFileTransfer/GetDirectoriesWithFileResponse")]
        System.Threading.Tasks.Task<string[]> GetDirectoriesWithFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/BackupAndChangeFiles", ReplyAction="http://tempuri.org/IFileTransfer/BackupAndChangeFilesResponse")]
        void BackupAndChangeFiles(string oldName, string[] allDirectoriesFromPath, string pathOfFileForInstalling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/BackupAndChangeFiles", ReplyAction="http://tempuri.org/IFileTransfer/BackupAndChangeFilesResponse")]
        System.Threading.Tasks.Task BackupAndChangeFilesAsync(string oldName, string[] allDirectoriesFromPath, string pathOfFileForInstalling);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileData {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream stream;
        
        public FileData() {
        }
        
        public FileData(string fileName, System.IO.Stream stream) {
            this.fileName = fileName;
            this.stream = stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToServerResponse {
        
        public UploadFileToServerResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransferChannel : MIEWpf.FileService.IFileTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransferClient : System.ServiceModel.ClientBase<MIEWpf.FileService.IFileTransfer>, MIEWpf.FileService.IFileTransfer {
        
        public FileTransferClient() {
        }
        
        public FileTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MIEWpf.FileService.EStatusOfOperation FileInstall(string filePath, string[] pathOfExistsFiles) {
            return base.Channel.FileInstall(filePath, pathOfExistsFiles);
        }
        
        public System.Threading.Tasks.Task<MIEWpf.FileService.EStatusOfOperation> FileInstallAsync(string filePath, string[] pathOfExistsFiles) {
            return base.Channel.FileInstallAsync(filePath, pathOfExistsFiles);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIEWpf.FileService.UploadFileToServerResponse MIEWpf.FileService.IFileTransfer.UploadFileToServer(MIEWpf.FileService.FileData request) {
            return base.Channel.UploadFileToServer(request);
        }
        
        public void UploadFileToServer(string fileName, System.IO.Stream stream) {
            MIEWpf.FileService.FileData inValue = new MIEWpf.FileService.FileData();
            inValue.fileName = fileName;
            inValue.stream = stream;
            MIEWpf.FileService.UploadFileToServerResponse retVal = ((MIEWpf.FileService.IFileTransfer)(this)).UploadFileToServer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MIEWpf.FileService.UploadFileToServerResponse> MIEWpf.FileService.IFileTransfer.UploadFileToServerAsync(MIEWpf.FileService.FileData request) {
            return base.Channel.UploadFileToServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<MIEWpf.FileService.UploadFileToServerResponse> UploadFileToServerAsync(string fileName, System.IO.Stream stream) {
            MIEWpf.FileService.FileData inValue = new MIEWpf.FileService.FileData();
            inValue.fileName = fileName;
            inValue.stream = stream;
            return ((MIEWpf.FileService.IFileTransfer)(this)).UploadFileToServerAsync(inValue);
        }
        
        public string[] GetDirectoriesWithFile(string fileName) {
            return base.Channel.GetDirectoriesWithFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDirectoriesWithFileAsync(string fileName) {
            return base.Channel.GetDirectoriesWithFileAsync(fileName);
        }
        
        public void BackupAndChangeFiles(string oldName, string[] allDirectoriesFromPath, string pathOfFileForInstalling) {
            base.Channel.BackupAndChangeFiles(oldName, allDirectoriesFromPath, pathOfFileForInstalling);
        }
        
        public System.Threading.Tasks.Task BackupAndChangeFilesAsync(string oldName, string[] allDirectoriesFromPath, string pathOfFileForInstalling) {
            return base.Channel.BackupAndChangeFilesAsync(oldName, allDirectoriesFromPath, pathOfFileForInstalling);
        }
    }
}
